var config = {
    "refreshInterval": 1000,
    "showAnalog": true,
    "showDigital": true,
    "24hour": false,
    "displayMinutes": true,
    "displaySeconds": true,
    "displayMilliseconds": false,
    "analogDisplayHoursIndicator": true,
    "analogDisplayMinutesIndicator": true,
    "analogDisplaySecondsIndicator": true,
    "analogDisplayHoursMarks": true,
    "analogDisplaySecondsMarks": true,
    "romanize": true,
    "timezone": "Europe/Warsaw",
};
